[CmdletBinding()]
param(
	[switch]$SkipBenchmark
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$benchmarkProjectPath = Join-Path $repositoryRoot 'PerformanceCI.Benchmarks\PerformanceCI.Benchmarks.csproj'
$integrationProjectPath = Join-Path $repositoryRoot 'PerformanceCI.Integration\PerformanceCI.Integration.csproj'
$readmePath = Join-Path $repositoryRoot 'README.md'
$startMarker = '<!-- PERFORMANCE-REPORT:START -->'
$endMarker = '<!-- PERFORMANCE-REPORT:END -->'

if (-not $SkipBenchmark) {
	foreach ($projectPath in @($benchmarkProjectPath, $integrationProjectPath)) {
		dotnet run --project $projectPath --configuration Release
		if ($LASTEXITCODE -ne 0) {
			throw "Performance benchmark failed for $projectPath with exit code $LASTEXITCODE."
		}
	}
}

# Each runner writes perf-report.txt next to its own binary.
$reportFiles = @(
	(Get-ChildItem "$repositoryRoot\PerformanceCI.Benchmarks\bin\Release" -Recurse -Filter 'perf-report.txt' -ErrorAction SilentlyContinue | Sort-Object LastWriteTime | Select-Object -Last 1),
	(Get-ChildItem "$repositoryRoot\PerformanceCI.Integration\bin\Release" -Recurse -Filter 'perf-report.txt' -ErrorAction SilentlyContinue | Sort-Object LastWriteTime | Select-Object -Last 1)
) | Where-Object { $_ -ne $null }

if ($reportFiles.Count -eq 0) {
	throw "No perf-report.txt was found under PerformanceCI.Benchmarks or PerformanceCI.Integration."
}

$reportContent = ($reportFiles | ForEach-Object {
	$reportDir = $_.DirectoryName
	$projectName = if ($reportDir -like '*PerformanceCI.Benchmarks*') { 'PerformanceCI.Benchmarks' } elseif ($reportDir -like '*PerformanceCI.Integration*') { 'PerformanceCI.Integration' } else { 'PerformanceCI' }
	"### $projectName"
	''
	(Get-Content -Path $_.FullName -Raw).Trim()
	''
}) -join [Environment]::NewLine
$environment = "OS: $([System.Environment]::OSVersion.VersionString); Runtime: $([System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription); Generated: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss')) UTC"
$managedSection = @(
	$startMarker
	'## Performance report'
	''
	'> Generated by running `PerformanceCI.Benchmarks` and `PerformanceCI.Integration`. Results are machine-specific and intended for regression tracking, not cross-machine comparison.'
	''
	$environment
	''
	$reportContent.Trim()
	$endMarker
) -join [Environment]::NewLine

if (Test-Path $readmePath) {
	$readmeContent = Get-Content -Path $readmePath -Raw
} else {
	$readmeContent = "# PerformanceCI$([Environment]::NewLine)$([Environment]::NewLine)"
}

$escapedStart = [Regex]::Escape($startMarker)
$escapedEnd = [Regex]::Escape($endMarker)
$replacementPattern = "(?s)$escapedStart.*?$escapedEnd"
if ($readmeContent -match $replacementPattern) {
	$readmeContent = [Regex]::Replace($readmeContent, $replacementPattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $managedSection })
} else {
	$readmeContent = $readmeContent.TrimEnd() + [Environment]::NewLine + [Environment]::NewLine + $managedSection + [Environment]::NewLine
}

Set-Content -Path $readmePath -Value $readmeContent -Encoding utf8
Write-Host "Updated $readmePath from $($reportFiles.Count) performance report(s)."